version: "3.9"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./db:/data/db
  app:
    container_name: backend-app
    depends_on:
      - mongodb
    build:
      context: ../..
      dockerfile: ./packages/api/Dockerfile.prod
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./src:/app/packages/api/src
      - ../../node_modules:/app/node_modules
      - ./node_modules:/app/packages/api/node_modules
    stdin_open: true
    tty: true

volumes:
  db:
