# name: Hello world
# run-name: ${{github.actor}} is testing out Github actions ğŸš€
on: push
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{github.event_name}} event."
      - run: echo "ğŸ§ The job is now running on a ${{runner.os}} server hosted on Github"
      - run: echo "ğŸ” The name of the branch is ${{github.ref}} and your repository is ${{github.repository}}"
      - name: Check out the repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{github.repository}} has been cloned to the ${{runner.os}} runner"
      - run: echo "ğŸ–¥ï¸ We are now ready to test your code in the runner"
      - name: List the files in the repository
        run: |
          ls ${{github.workspace}}
      - name: Make a new directory and add a file to it
        run: |
          mkdir distro
          touch maga.js
          mv maga.js distro
      - name: list files again
        run: find . -name distro
      - run: echo "ğŸ The job's status is ${{job.status}}"
